name: CI

on:
  push:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  reproduction:
    name: Reproduction
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Test (AUTOLOAD=false)
        run: AUTOLOAD=false npm run test

      - name: Test (AUTOLOAD=true)
        run: AUTOLOAD=true npm run test
